---
name: "Build and assembly without test Scala"
description: "Build and assembly Scala project without running unit tests"
runs:
  using: "composite"
  steps:
  - name: clean
    shell: bash
    run: sbt clean
  - name: update
    shell: bash
    run: sbt update
  - name: compile
    shell: bash
    run: sbt compile
  - name: Assembly fat jar file
    shell: bash
    run: sbt assembly
