---
name: 'Perform a Docker Image scan with Black Duck'
description: |
  The following Git Action performs a docker image scan in a layer-based or single-base manner.
  In order to make use of this action, it is important to configure the AWS credentials for the environment in which the
  repository is located.
  The ECR registry needs to have been set up in advance to enable its usage in this action by passing it as a parameter.

inputs:
  awsRegion:
    description: "Passes the AWS Region for login"
    required: true
  ecrReg:
    description: "Passes the ECR Registry for login"
    required: true
  projectName:
    description: "Name to be used for the project in Black Duck"
    required: true
  codeLocationSuffix:
    description: "Name to be used for the version in Black Duck"
    required: true
  tags:
    description: "Includes relevant information regarding the project distribution for license categorization"
    required: false
    default: "none"
  repositoryLink:
    description: "Link to the Repository where the Docker Image on ECR is"
    required: true
  repositoryName:
    description: "Repository Name in ECR where the Docker Image is placed"
    required: true
  dockerImageTag:
    description: "Tag from the docker image to be used"
    required: true
  blackDuckToken:
    description: "Token used to submit the scans to Black Duck dashboards"
    required: true
  blackDuckURL:
    description: "URL from the Black Duck Dashboards where the scans will be deployed"
    required: true
    default: "https://bdh.aws.cloud.vwgroup.com"
  releaseTag:
    description: "ID of the currently released version. In case a merge to master was the trigger of the action, 'nonrelease' should be passed"
    required: true
  userGroup:
    description: "User group to which the project should be assigned"
    required: true
    default: "cap"
  groupName:
    description: "Project group name to which the project should be assigned"
    required: false
    default: "Black Duck Project Groups"
  codeLocationName:
    description: "Sets the name for the created scan. If nothing given uses the name for the version"
    required: false
    default: ""
  isRelease:
    description: "true/false value that checks if it is a release. Defaults to false."
    required: false
    default: "false"
  mainBranchName:
    description: "Name given to main branch."
    required: false
    default: "main"
  shouldGenerateReport:
    description: "Boolean value to generate reports at <reportPath>. Default: false. Also see: https://devstack.vwgroup.com/confluence/pages/viewpage.action?pageId=1745096719"
    required: false
    default: "false"
  tokenConfluence:
    description: "Confluence token"
    required: true
  reportPath:
    description: "reportPath"
    required: true
    default: "./report"
  confluenceSpace:
    description: "Confluence space where the artifacts should be uploaded to"
    required: true
  scanPrefix:
    required: false
    description: "Used to properly distinguish the uploaded files, when you have to run more than one scan for each release"
    default: "default"
  confluenceUsername:
    description: "Username which is used to upload the required BlackDuck files to confluence"
    required: true
  repoName:
    description: "Name of the repo. Is used to categorise releases."
    required: true
  confluencePageId:
    description: "PageId to which BlackDuck files are uploaded"
    required: true
  detectTimeout:
    description: "The timeout for the detect job which is passed to --detect.timeout"
    required: false
    default: "1200"
  working-directory:
    description: 'Directory to work in'
    required: false
    default: "."
  devstack-user:
    description: 'Devstack user ID'
    required: true
  devstack-artifactory-token:
    description: 'Devstack token jfrog artifactory'
    required: true
  skip-plausi-check:
    description: 'Skips the Plausi Check validation'
    required: false
    default: false
  upload-plausicheck-results:
    description: 'Whether to upload PlausiCheck artifacts to GitHub'
    required: false
    default: true
  cleanup:
    description: 'Cleanup'
    required: false
    default: true

runs:
  using: "composite"
  steps:
  - name: Create Timestamp
    shell: bash
    run: |
      timestamp=$(date +%Y%m%d%H%M%S)
      echo "timestamp=$timestamp" >> "$GITHUB_ENV"

  - name: Create Temp Dir
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: mkdir -p blackduck_tmp

  - name: Get Detect Script
    shell: bash
    working-directory: ${{ inputs.working-directory }}/blackduck_tmp
    run: |
      curl -s -L -O https://detect.blackduck.com/detect10.sh
      chmod +x detect10.sh

  - name: Install required libraries for the scans
    shell: bash
    run: |
      python -m pip install blackduck
      python -m pip install pandas

  - name: Run Docker Image Scan
    shell: bash
    run: |
      releaseArgs=()
      if [[ "${{ inputs.isRelease }}" == "true" ]]; then
        releaseArgs+=("--detect.project.clone.categories=ALL")
        releaseArgs+=("--detect.policy.check.fail.on.severities=ALL")
        releaseArgs+=("--detect.clone.project.version.name=${{ inputs.mainBranchName }}")
      fi
      aws ecr get-login-password --region "${{ inputs.awsRegion }}" \
      | docker login --username AWS --password-stdin "${{ inputs.ecrReg }}"
      echo "Running Black Duck scan..."

      bash ./blackduck_tmp/detect10.sh \
        --blackduck.url="${{ inputs.blackDuckURL }}" \
        --blackduck.api.token="${{ inputs.blackDuckToken }}" \
        --detect.project.name="${{ inputs.projectName }}" \
        --detect.project.version.name="${{ inputs.releaseTag }}" \
        --detect.project.tags="${{ inputs.tags }}" \
        --detect.code.location.name="${{ inputs.projectName }}/${{ inputs.releaseTag }}" \
        --detect.docker.image="${{ inputs.repositoryLink }}/${{ inputs.repositoryName }}:${{ inputs.dockerImageTag }}" \
        --blackduck.trust.cert=true \
        --detect.tools.excluded=DETECTOR,BINARY_SCAN \
        --detect.timeout="${{ inputs.detectTimeout }}" \
        --detect.project.user.groups="${{ inputs.userGroup }}" \
        --detect.project.version.update=true \
        "${releaseArgs[@]}" \
        2>&1 | tee blackduck_tmp/bdhscan.txt

      echo "scan_status=$?" >> "$GITHUB_ENV"

  - name: Extract Version Link
    if: ${{ inputs.skip-plausi-check != 'true' }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      version_link=`grep -o 'https://bdh.aws.cloud.vwgroup.com/.*/components' blackduck_tmp/bdhscan.txt`
      echo "version_link=$version_link"
      echo "version_link=$version_link" >> "$GITHUB_ENV"
      echo "Link to project version in OSS Scanning Software (e.g. Black Duck):" > blackduck_tmp/blackduck_oss_scanner_url.txt
      echo "$version_link" >> blackduck_tmp/blackduck_oss_scanner_url.txt

  - name: Login to Devstack-Docker-Artifactory
    if: ${{ inputs.skip-plausi-check != 'true' }}
    uses: docker/login-action@v3
    with:
      registry: bdh-docker.docker.devstack.vwgroup.com
      username: ${{ inputs.devstack-user }}
      password: ${{ inputs.devstack-artifactory-token }}

  - name: Run Plausi Check
    if: ${{ inputs.skip-plausi-check != 'true' }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      BDH_TOKEN: ${{ inputs.blackDuckToken }}
    run: |
      work_path=`pwd`
      docker run --mount type=bind,source="${work_path}/blackduck_tmp",target=/data \
      bdh-docker.docker.devstack.vwgroup.com/plausicheck \
      $version_link \
      $BDH_TOKEN
      echo "<details>" > $GITHUB_STEP_SUMMARY
      echo "<summary>PlausiCheck-Report</summary>" >> $GITHUB_STEP_SUMMARY
      cat blackduck_tmp/PlausiCheck_BDH.html >> $GITHUB_STEP_SUMMARY
      echo "</details>" >> $GITHUB_STEP_SUMMARY

  - name: Archive production artifacts
    if: ${{ inputs.skip-plausi-check != 'true' && inputs.upload-plausicheck-results == 'true' }}
    uses: actions/upload-artifact@v6
    with:
      name: ${{ github.job }}-plausi-check-results_${{ env.timestamp }}
      path: |
        ${{ inputs.working-directory }}/blackduck_tmp/PlausiCheck_BDH.json
        ${{ inputs.working-directory }}/blackduck_tmp/PlausiCheck_BDH.html
        ${{ inputs.working-directory }}/blackduck_tmp/blackduck_oss_scanner_url.txt

  - name: CleanUp
    if: ${{ inputs.cleanup == 'true' }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      rm -rf blackduck_tmp
      rm -f detect9.sh bdhscan.txt
