---
name: 'CAP Terraform'
description: Conditionally remove Terraform lock from DynamoDB.

inputs:
  tf-lock-id:
    description: Terraform LockID to remove.
    required: true
  tf-state-name:
    description: DynamoDB table name for locks.
    required: true
  aws-region:
    description: AWS region of DynamoDB table.
    required: true
  force:
    description: Force removal ignoring lock age (true/false).
    default: 'false'
    required: false
  role-to-assume:
    description: Optional IAM role ARN to assume.
    default: ''
    required: false
  role-session-name:
    description: Optional session name for assumed role.
    default: ''
    required: false

runs:
  using: composite
  steps:
  - name: Authenticate with OIDC Role
    if: inputs.role-to-assume != ''
    uses: aws-actions/configure-aws-credentials@v6
    with:
      aws-region: ${{ inputs.aws-region }}
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name != '' && inputs.role-session-name || github.event.repository.name }}
      mask-aws-account-id: false

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'

  - name: Install dependencies
    shell: bash
    run: |
      echo "Installing Python dependencies..."
      ls -lh ${{ github.action_path }}
      pip install -r "${{ github.action_path }}/requirements.txt"

  - name: Remove Terraform LockID via Python
    shell: bash
    run: |
      python "${{ github.action_path }}/remove_lock.py" \
        --lock-id "${{ inputs.tf-lock-id }}" \
        --table "${{ inputs.tf-state-name }}" \
        --region "${{ inputs.aws-region }}" \
        $( [[ "${{ inputs.force }}" == 'true' ]] && echo "--force" )
