---
# For pipelines integrating SonarQube analysis, please use the 2-step process with
# actions test-with-coverage-scala/action.yml and build-without-test-scala/action.yml
name: "Scala build"
description: "Build scala project"
runs:
  using: "composite"
  steps:
  - name: clean
    shell: bash
    run: sbt clean
  - name: update
    shell: bash
    run: sbt update
  - name: compile
    shell: bash
    run: sbt compile
  - name: test
    shell: bash
    run: sbt -v test
  - name: Assembly fat jar file
    shell: bash
    run: sbt assembly
