---
name: 'Install CAP Master SSH Key'
description: |
  Install master ssh key from CAP for all hosts cap-*.
  Historically, CAP used different SSH keys. To allow this setup with Terraform
  different modules, CAP had to replace the github.com with cap-name-of-repo.
  For this reason, the master ssh key is saved for all hostname starting with
  cap-*.
inputs:
  ssh-private-key:
    description: "SSH Private Key Content"
    required: true

runs:
  using: "composite"
  steps:
  - name: "Ensure SSH base dir/file"
    shell: bash
    run: |
      mkdir ~/.ssh || echo "~/.ssh dir already exists"
      touch ~/.ssh/known_hosts || echo "~/.ssh/known_hosts already exists"
      touch ~/.ssh/config || echo "~/.ssh/config already exists"
      cat <<EOF >> ~/.ssh/known_hosts
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      EOF
  - name: "Save Master SSH Key"
    shell: bash
    env:
      SSH_KEY: ${{ inputs.ssh-private-key }}
      MASTER_KEY_NAME: id_rsa
    run: |
      echo "$SSH_KEY" > ~/.ssh/$MASTER_KEY_NAME
      sudo chmod 600 ~/.ssh/$MASTER_KEY_NAME
      sudo cat <<EOF >> ~/.ssh/config
      Host cap-*
        HostName github.com
        User git
        IdentityFile ~/.ssh/$MASTER_KEY_NAME
        IdentitiesOnly yes
      EOF
      ssh -T git@github.com || echo -
