---
name: 'Base Signature Scan'
description: |
  The following Git Action performs a signature scan on the current directory.
  This action is specially useful on the following scenarios:
  - When scanning Terraform files: In order to run the scan, the Terraform dependencies need to have been previously downloaded, whcih is
    achieved by running the "terraform init" command. No directory switching should be performed either while attaining the dependencies nor
    before calling this action. Doing so may result in the dependencies not being found.
  - When scanning Git repositories: The check out from the repository/ies must be performed in advance before executing this action. They
    need to be placed in the starting directory, or it is needed to ensure that the action is called in the directory above to where the
    repository(ies) are extracted, otherwise not all the dependencies might be found.
inputs:
  projectName:
    description: "Name to be used for the project in Black Duck"
    required: true
  codeLocationSuffix:
    description: "Name to be used for the version in Black Duck"
    required: true
  tags:
    description: "Includes relevant information regarding the project distribution for license categorization"
    required: false
    default: "none"
  releaseTag:
    description: "ID of the currently released version. In case a merge to master was he trigger of the action, 'nonrelease' should be passed"
    required: true
  blackDuckToken:
    description: "Token used to submit the scans to black duck dashboards"
    required: true
  blackDuckURL:
    description: "URL from the Black Duck Dashboards where the scans will be deployed"
    required: true
  userGroup:
    description: "User group to which the project should be assigned"
    required: true
    default: "cap"
  groupName:
    description: "Project group name to which the project should be assigned"
    required: true
    default: "cap"
  relativePathToScan:
    description: "Receives a relative path to scan in case not the current directory is targeted. If nothing given automatically scans the whole repo (Intended\
      \ for terraform scans)"
    required: true
    default: "./terraform/"
  codeLocationName:
    description: "Sets the name for the created scan. If nothing given uses the name for the version"
    required: false
    default: 0
  isRelease:
    description: "true/false value that checks if it is a release. Defaults to false."
    required: false
    default: false
  mainBranchName:
    description: "Name given to main branch."
    required: false
    default: main
  shouldGenerateReport:
    description: "Boolean value to generate reports at <reportPath>. Default: false. Also see: https://devstack.vwgroup.com/confluence/pages/viewpage.action?pageId=1745096719"
    required: false
    default: "false"
  tokenConfluence:
    description: "Confluence token"
    required: true
  reportPath:
    description: "reportPath"
    required: true
    default: "./report"
  confluenceSpace:
    description: "Confluence space where the artifacts should be uploaded to"
    required: true
  scanPrefix:
    required: false
    description: "Used to properly distinguish the uploaded files, when you have to run more than one scan for each release"
  confluenceUsername:
    description: "Username which is used to upload the required BlackDuck files to confluence"
    required: true
  repoName:
    description: "Name of the repo. Is used to categorise releases."
    required: true
  confluencePageId:
    description: "PageId to which BlackDuck files are uploaded"
    required: true
runs:
  using: "composite"
  steps:
  - name: "Run Detect from Black Duck to scan the Git Repository"
    shell: bash
    run: |
      cd ${{ inputs.relativePathToScan }}
      releaseArgs=()
      if [ ${{inputs.isRelease}} == "true" ];then
        releaseArgs+=( "--detect.project.version.phase=RELEASED" )
        releaseArgs+=( "--detect.project.clone.categories=ALL" )
        releaseArgs+=( "--detect.clone.project.version.name=${{inputs.mainBranchName}}" )
        releaseArgs+=( "--detect.policy.check.fail.on.severities=ALL" )
      fi
      bash <(curl -s https://detect.blackduck.com/detect9.sh) \
      --blackduck.url=${{ inputs.blackDuckURL }} \
      --blackduck.api.token=${{ inputs.blackDuckToken }} \
      --detect.project.name=${{ inputs.projectName }} \
      --detect.project.version.name=${{ inputs.releaseTag }} \
      --detect.project.tags=${{ inputs.tags }} \
      --detect.code.location.name=${{ inputs.projectName }}/${{ inputs.releaseTag }}/${{ inputs.codeLocationSuffix }} \
      --detect.project.force.update=true \
      --blackduck.trust.cert=true \
      --detect.tools=IAC_SCAN \
      --detect.iac.scan.paths=. \
      --detect.project.user.groups=${{ inputs.userGroup }} \
      --detect.project.group.name=${{ inputs.groupName }} ${releaseArgs[@]} \
      2>&1 | tee scan_log.txt
  - name: Run Upload of BlackDuck files in case of Release
    uses: actions/setup-python@v6
    with:
      python-version: "3.10"
  - name: Install Libs
    run: pip3 install requests==2.31.0
    shell: bash
  - name: Upload Report
    if: ${{ inputs.isRelease != '' }}
    run: python '${{ github.action_path }}/../upload_release_scan.py' "${{ inputs.confluenceUsername }}" "${{ inputs.tokenConfluence }}" "${{ inputs.confluencePageId
      }}" "${{ inputs.releaseTag }}" "${{ inputs.repoName }}" "${{ inputs.confluenceSpace }}" "${{ inputs.scanPrefix }}" "${{ inputs.relativePathToScan
      }}/scan_log.txt"
    shell: bash
