---
name: 'Perform a Docker Image scan with Black Duck'
description: |
  The following Git Action performs a docker image scan in a layer-base or single-base manner.
  In order to make use of this action, it is important to configure the AWS credentials for the environment in whcih the
    repository is located. This can be achieved by using the action "aws-actions/configure-aws-credentials@v6"
  The ECR registry needs to have been set up in advance to enable it's usage on this action by passing it as a parametr.
inputs:
  awsRegion:
    description: "Passes the AWS Region for login"
    required: true
  ecrReg:
    description: "Passes the ECR Registry for login"
    required: true
  projectName:
    description: "Name to be used for the project in Black Duck"
    required: true
  codeLocationSuffix:
    description: "Name to be used for the version in Black Duck"
    required: true
  tags:
    description: "Includes relevant information regarding the project distribution for license categorization"
    required: false
    default: "none"
  repositoryLink:
    description: "Link to the Repository where the Docker Image on ECR is"
    required: true
  repositoryName:
    description: "Repository Name in ECR where the Docker Image is placed"
    required: true
  dockerImageTag:
    description: "Tag from the docker image to be used"
    required: true
  blackDuckToken:
    description: "Token used to submit the scans to black duck dashboards"
    required: true
  blackDuckURL:
    description: "URL from the Black Duck Dashboards where the scans will be deployed"
    required: true
  releaseTag:
    description: "ID of the currently released version. In case a merge to master was he trigger of the action, 'nonrelease' should be passed"
    required: true
  userGroup:
    description: "User group to which the project should be assigned"
    required: true
    default: "cap"
  groupName:
    description: "Project group name to which the project should be assigned"
    required: true
    default: "cap"
  codeLocationName:
    description: "Sets the name for the created scan. If nothing given uses the name for the version"
    required: false
    default: 0
  isRelease:
    description: "true/false value that checks if it is a release. Defaults to false."
    required: false
    default: false
  mainBranchName:
    description: "Name given to main branch."
    required: false
    default: main
runs:
  using: "composite"
  steps:
  - name: "Install required libraries for the scans"
    shell: bash
    run: |
      python -m pip install blackduck
      python -m pip install pandas

  - name: "Run Docker Image Scan"
    shell: bash
    run: |
      releaseArgs=()
      if [ ${{inputs.isRelease}} == "true" ];then
        releaseArgs+=( "--detect.project.clone.categories=ALL" )
        releaseArgs+=( "--detect.clone.project.version.name=${{inputs.mainBranchName}}" )
        releaseArgs+=( "--detect.policy.check.fail.on.severities=ALL" )
      fi
      aws ecr get-login-password --region ${{ inputs.awsRegion }} \
      | docker login --username AWS --password-stdin ${{ inputs.ecrReg }}
      bash <(curl -s https://detect.blackduck.com/detect9.sh) \
      --blackduck.url=${{ inputs.blackDuckURL }} \
      --blackduck.api.token=${{ inputs.blackDuckToken }} \
      --detect.project.name=${{ inputs.projectName }} \
      --detect.project.version.name=${{ inputs.releaseTag }} \
      --detect.project.tags=${{ inputs.tags }} \
      --detect.code.location.name=${{ inputs.projectName }}/${{ inputs.releaseTag }}/${{ inputs.codeLocationSuffix }} \
      --detect.docker.image=${{ inputs.RepositoryLink }}/${{ inputs.RepositoryName }}:${{ inputs.dockerImageTag }} \
      --detect.tools.excluded=DETECTOR,BINARY_SCAN \
      --detect.project.user.groups=${{ inputs.userGroup }} \
      --detect.project.group.name=${{ inputs.groupName }} ${releaseArgs[@]}
