---
name: 'Ensure compliance'

on:
  pull_request:
    branches:
    - master
    - main
  push:
    branches:
    - master
    - main
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  TF_VERSION: '0.14.8'
  TERRAFORM_ROOT_DIR: ''

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    env:
      SKIP: terraform_validate
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Pre-Commit
      uses: pre-commit/action@v3.0.0

  checkov:
    name: Configuration Checks (checkov)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v3
    - name: Run Checkov
      run: docker container run -t -v ${{ github.workspace }}/${{ env.TERRAFORM_ROOT_DIR }}:/tf bridgecrew/checkov -d /tf --quiet
