---
name: 'Create/use parent project and add the performed scans'
description: |
  The following Git Action finds or creates a parent project used for the repository in which each version will be added along all their
    related scans.
  Ensure to be in the parent directory where the cap-github-actions repository has been checked out.
inputs:
  projectName:
    description: "Name to be used for the project in Black Duck"
    required: true
  blackDuckToken:
    description: "Token used to submit the scans to black duck dashboards"
    required: true
  blackDuckURL:
    description: "URL from the Black Duck Dashboards where the scans will be deployed"
    required: true
  releaseTag:
    description: "ID of the currently released version."
    required: true
  tags:
    description: "Includes relevant information regarding the project distribution for license categorization"
    required: false
    default: "none"
  userGroup:
    description: "User group to which the project should be assigned"
    required: false
    default: "cap"

runs:
  using: "composite"
  steps:
  - name: "Perform the integration"
    shell: bash
    run: |
      python -m pip install blackduck
      python -m pip install pandas
      cp ./blackduck/actions/blackduck-scan/assets/.restconfig.json .
      sed -i s/"{BLACK_DUCK_TOKEN}"/"${{ inputs.blackDuckToken }}"/ .restconfig.json
      sed -i s@"{BLACK_DUCK_URL}"@"${{ inputs.blackDuckURL }}"@ .restconfig.json
      echo ${{ inputs.tags }}
      python ./blackduck/actions/blackduck-scan/assets/bd_project_integrator.py ${{ inputs.projectName }} ${{ inputs.releaseTag }} \
        "${{ inputs.tags }}" ${{ inputs.userGroup }}
