---
name: 'CAP Terraform'
description: |
  Create the Terraform plan
inputs:
  artifact-prefix:
    description: "Extra prefix for artifact's name. To distinguish artifacts possibly named the same"
    default: ''
    required: false
  python-version:
    description: "Python version"
    required: false
    default: ''
  tf-step:
    description: "String variable for terraform step. Valid options are : 'plan-out', 'apply-auto-approve', 'plan-destroy', 'destroy-auto-approve', 'custom-tf-command'"
    required: true
  access-key-id:
    description: "access key id"
    default: ''
    required: false
  secret-access-key:
    description: "access key"
    default: ''
    required: false
  aws-region:
    description: "aws region"
    required: true
  aws-profile-name:
    description: "name of the aws profile to create with the provided credentials"
    default: "default"
    required: false
  role-to-assume:
    description: "Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than\
      \ with the provided credentials"
    default: ''
    required: false
  cap-ssh-private-key:
    description: "cap ssh private key"
    required: true
  disable-commenter:
    description: "disable the TF PR commenter to avoid warning messages"
    required: false
    default: "true"
  project:
    description: "name of project"
    required: false
  tf-root-dir:
    description: "Terraform root directory"
    default: "terraform/environments"
    required: false
  tf-environment:
    description: "Terraform environment"
    required: true
  stage:
    description: "Stage name"
    required: true
  state-lock-timeout:
    description: "Timeout in mins for which state file will be locked"
    default: "20m"
    required: false
  tf-workspace:
    description: "Workspace"
    required: true
  tf-bucket-base-name:
    description: "Terraform bucket base name"
    default: "terraform-backend"
    required: false
  tf-dynamo-base-name:
    description: "Terraform dynamo base name"
    default: "terraform-state-lock"
    required: false
  tf-state-additional-prefix:
    description: "tf additional prefix"
    default: ''
    required: false
  fetch-from-secretsmanager:
    description: "Whether to try and pull TF Vars from Secrets Manager or not"
    default: "true"
    required: false
  tf-bucket-name:
    description: "Terraform bucket full name"
    default: 'BucketNameNotSet'
    required: false
  tf-dynamo-name:
    description: "Terraform dynamo table full name"
    default: 'DynamoNameNotSet'
    required: false
  tf-state-prefix:
    description: "Prefix to save the state in"
    default: 'TFStatePrefixNotSet'
    required: false
  tf-parallelism:
    description: "Limit the number of concurrent operations as Terraform walks the graph. Defaults to 10."
    default: 10
    required: false
  tf-refresh:
    description: "Whether to refresh resource metadata before executing the plan"
    default: true
    required: false
  tfswitch-version:
    description: "Tfswitch action version. In case the version needs to be specified because of failing releases."
    default: "v1.3.0"
    required: false
  role-duration-seconds:
    description: "Maximum session duration (in seconds) that you want to set for the specified role. This setting can have a value from 1 hour to 12 hours."
    default: 3600
    required: false
  custom-tf-command:
    description: "The custom terraform command to run if tf-step is set to custom-tf-command"
    default: ""
    required: false
  role-session-name:
    description: 'Role session name'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
  - name: Setup Python
    if: inputs.python-version != ''
    uses: actions/setup-python@v6
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install VirtualEnv
    shell: bash
    if: ${{ inputs.tf-step == 'apply-auto-approve' && inputs.python-version != '' }}
    run: pip3 install virtualenv
  - name: Install tfswitch
    shell: bash
    run: |
      curl -o install.sh https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
      chmod 755 install.sh
      ./install.sh -b ~/.tfswitch/bin ${{ inputs.tfswitch-version }}
      echo "~/.tfswitch/bin" >> $GITHUB_PATH
      rm -f /usr/local/bin/terraform > /dev/null 2>&1
  - name: Install Terraform
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      tfswitch
  - name: Configure AWS Credentials
    if: inputs.access-key-id != '' && inputs.secret-access-key != ''
    shell: bash
    run: |
      aws configure set aws_access_key_id ${{ inputs.access-key-id }} --profile ${{ inputs.aws-profile-name }}
      aws configure set aws_secret_access_key ${{ inputs.secret-access-key }} --profile ${{ inputs.aws-profile-name }}
      aws configure set region ${{ inputs.aws-region }} --profile ${{ inputs.aws-profile-name }}
  - name: Authenticate with OIDC role
    if: inputs.role-to-assume != ''
    uses: aws-actions/configure-aws-credentials@v6
    with:
      aws-region: ${{ inputs.aws-region }}
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name != '' && inputs.role-session-name || github.event.repository.name }}
      mask-aws-account-id: false
      role-duration-seconds: ${{ inputs.role-duration-seconds }}
  - name: Setup Master SSH Key
    uses: ./shared/actions/cap-master-ssh-key
    with:
      ssh-private-key: ${{ inputs.cap-ssh-private-key }}
  - name: Set env vars
    shell: bash
    run: |
      echo ARTIFACT_NAME_PREFIX=${{ inputs.artifact-prefix }}${{ inputs.stage }}-${{ inputs.tf-environment }}-${{ inputs.tf-workspace }} >> $GITHUB_ENV
      echo PATH_PREFIX=${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }} >> $GITHUB_ENV
  - name: Create .tfvars
    if: contains(inputs.fetch-from-secretsmanager, 'true') && ( inputs.tf-step == 'plan-out' || inputs.tf-step == 'plan-destroy' || inputs.tf-step == 'destroy-auto-approve')
    uses: ./shared/actions/create-tfvars-from-secretsmanager
    with:
      secret-name: github-actions-${{ inputs.project }}-${{ inputs.tf-environment }}-${{ inputs.stage }}
      tf-vars-file-path: ${{ github.workspace }}/${{ env.PATH_PREFIX }}/${{ inputs.tf-environment }}.auto.tfvars
  - uses: actions/download-artifact@v7
    if: ${{ inputs.tf-step == 'apply-auto-approve' }}
    with:
      name: ${{ env.ARTIFACT_NAME_PREFIX }}-plan-out
      path: ${{ env.PATH_PREFIX }}
  - uses: actions/download-artifact@v7
    if: ${{ inputs.tf-step == 'destroy-auto-approve' }}
    with:
      name: ${{ env.ARTIFACT_NAME_PREFIX }}-plan-destroy
      path: ${{ env.PATH_PREFIX }}
  - name: Display project and user information
    shell: bash
    run: |
      echo WORKSPACE=${{ inputs.tf-workspace }} PROJECT=${{ inputs.project }} STAGE=${{ inputs.stage }} ENVIRONMENT=${{ inputs.tf-environment }}
      aws sts get-caller-identity
  - name: Set bucket and dynamo table names or create them if not specified as inputs
    shell: bash
    id: set-tf-backend-names
    run: |
      if [ '${{ inputs.tf-bucket-name }}' == 'BucketNameNotSet' ]
      then
        echo BUCKET=${{ inputs.project }}-${{ inputs.stage }}-${{ inputs.tf-bucket-base-name }}  >> $GITHUB_OUTPUT
      else
        echo BUCKET=${{ inputs.tf-bucket-name }} >> $GITHUB_OUTPUT
      fi

      if [ '${{ inputs.tf-dynamo-name }}' == 'DynamoNameNotSet' ]
      then
        echo DYNAMO_TABLE=${{inputs.project}}-${{ inputs.stage }}-${{ inputs.tf-dynamo-base-name }} >> $GITHUB_OUTPUT
      else
        echo DYNAMO_TABLE=${{ inputs.tf-dynamo-name }} >> $GITHUB_OUTPUT
      fi

      if [ '${{ inputs.tf-state-prefix }}' == 'TFStatePrefixNotSet' ]
      then
        echo KEY_PREFIX=analytics-vpc-${{ inputs.aws-region }}/${{ inputs.tf-state-additional-prefix }}${{ inputs.tf-environment }}/${{ inputs.tf-environment }}.tfstate >> $GITHUB_OUTPUT
        echo WORKSPACE_KEY_PREFIX=env: >> $GITHUB_OUTPUT
      else
        echo KEY_PREFIX=${{ inputs.tf-state-prefix }}/${{ inputs.tf-environment }}.tfstate >> $GITHUB_OUTPUT
        echo WORKSPACE_KEY_PREFIX=${{ inputs.tf-state-prefix }}/env: >> $GITHUB_OUTPUT
      fi

  - name: CAPSUPP Ancillary Info
    shell: bash
    env:
      KEY_PREFIX: ${{ steps.set-tf-backend-names.outputs.KEY_PREFIX }}
      WORKSPACE_KEY_PREFIX: ${{ steps.set-tf-backend-names.outputs.WORKSPACE_KEY_PREFIX }}
      DYNAMO_TABLE: ${{ steps.set-tf-backend-names.outputs.DYNAMO_TABLE }}
    run: |
      YELLOW_COLOR="\033[33m"    # Yellow for the message
      KEY_COLOR="\033[32m"       # Green for keys
      EQUALS_COLOR="\033[37m"    # Gray for '='
      VALUE_COLOR="\033[36m"     # Cyan for values
      RESET="\033[0m"

      echo -e "${YELLOW_COLOR}Printing LockID, in case of state lock issue provide these values to support team ${RESET}"
      echo -e "${YELLOW_COLOR} via CAPSUPP Ticket or link to this pipeline${RESET}"

      if [ ${{ inputs.tf-workspace }} = "default" ]; then
        if [ -n "$WORKSPACE_KEY_PREFIX" ]; then
          lockid="${WORKSPACE_KEY_PREFIX}/${KEY_PREFIX}"
        else
          lockid="${KEY_PREFIX}"
        fi
      else
        if [ -n "$WORKSPACE_KEY_PREFIX" ]; then
          lockid="${WORKSPACE_KEY_PREFIX}/${{inputs.tf-workspace}}/${KEY_PREFIX}"
        else
          lockid="${{inputs.tf-workspace}}/${KEY_PREFIX}"
        fi
      fi

      echo -e "${KEY_COLOR}DynamoDB Table${EQUALS_COLOR}=${VALUE_COLOR}${DYNAMO_TABLE}${RESET}"
      echo -e "${KEY_COLOR}KEY_PREFIX${EQUALS_COLOR}=${VALUE_COLOR}${KEY_PREFIX}${RESET}"
      echo -e "${KEY_COLOR}WORKSPACE_KEY_PREFIX${EQUALS_COLOR}=${VALUE_COLOR}${WORKSPACE_KEY_PREFIX}${RESET}"
      echo -e "${KEY_COLOR}LockID${EQUALS_COLOR}=${VALUE_COLOR}${DYNAMO_TABLE}/${lockid}${RESET}"

  - name: Terraform Init CAP 2.0
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      terraform init -backend-config=region=${{ inputs.aws-region }} \
        -backend-config=bucket=${{ steps.set-tf-backend-names.outputs.BUCKET }} \
        -backend-config=dynamodb_table=${{ steps.set-tf-backend-names.outputs.DYNAMO_TABLE }} \
        -backend-config=key=${{ steps.set-tf-backend-names.outputs.KEY_PREFIX }} \
        -backend-config=workspace_key_prefix=${{ steps.set-tf-backend-names.outputs.WORKSPACE_KEY_PREFIX }}
      terraform workspace select ${{ inputs.tf-workspace }} || terraform workspace new ${{ inputs.tf-workspace }}
  - name: Terraform Validate
    if: ${{ inputs.tf-step == 'plan-out' }}
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      terraform validate
  - name: Authenticate with OIDC role
    if: inputs.role-to-assume != ''
    uses: aws-actions/configure-aws-credentials@v6
    with:
      aws-region: ${{ inputs.aws-region }}
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name != '' && inputs.role-session-name || github.event.repository.name }}
      mask-aws-account-id: false
      role-duration-seconds: ${{ inputs.role-duration-seconds }}
  - name: Terraform Plan
    if: ${{ inputs.tf-step == 'plan-out' }}
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      terraform plan -input=false                       \
        -parallelism=${{inputs.tf-parallelism}}         \
        -refresh=${{ inputs.tf-refresh }}               \
        -lock-timeout=${{ inputs.state-lock-timeout }}  \
        -out=plan.out
      terraform show -json plan.out > ${{inputs.tf-workspace}}-${{inputs.stage}}-${{inputs.tf-environment}}-terraform.json

  - name: Terraform Custom Command
    if: ${{ inputs.tf-step == 'custom-tf-command' }}
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      ${{inputs.custom-tf-command}}

  - name: TF Report
    uses: liatrio/terraform-change-pr-commenter@v1.14.2
    if: ${{ inputs.tf-step == 'plan-out' && inputs.disable-commenter == 'false'}}
    with:
      json-file: ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}/${{inputs.tf-workspace}}-${{inputs.stage}}-${{inputs.tf-environment}}-terraform.json
      expand-comment: 'true'
      include-plan-job-summary: 'true'

  - name: TF Apply
    if: ${{ inputs.tf-step == 'apply-auto-approve' }}
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      terraform apply -input=false   \
        -parallelism=${{inputs.tf-parallelism}}        \
        -refresh=${{ inputs.tf-refresh }}              \
        -lock-timeout=${{ inputs.state-lock-timeout }}  \
        -auto-approve plan.out
  - name: Terraform Plan Destroy
    if: ${{ inputs.tf-step == 'plan-destroy' }}
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      terraform plan -input=false                       \
        -parallelism=${{inputs.tf-parallelism}}         \
        -refresh=true                                   \
        -lock-timeout=${{ inputs.state-lock-timeout }}  \
        -destroy                                        \
        -out=plan.out
  - name: Terraform Destroy
    if: ${{ inputs.tf-step == 'destroy-auto-approve'}}
    shell: bash
    run: |
      cd ${{ inputs.tf-root-dir }}/${{ inputs.tf-environment }}
      terraform destroy -input=false  \
        -parallelism=${{inputs.tf-parallelism}}         \
        -refresh=true                                   \
        -lock-timeout=${{ inputs.state-lock-timeout }}  \
        -auto-approve
  - name: Save Terraform Plan as Artifact
    uses: actions/upload-artifact@v6
    if: ${{ inputs.tf-step == 'plan-out' || inputs.tf-step == 'plan-destroy' }}
    with:
      name: ${{ env.ARTIFACT_NAME_PREFIX }}-${{ inputs.tf-step }}
      path: ${{ env.PATH_PREFIX }}/plan.out
  - name: Save Error State
    uses: actions/upload-artifact@v6
    if: ${{ (inputs.tf-step == 'apply-auto-approve' || inputs.tf-step == 'destroy-auto-approve') && failure() }}
    with:
      name: ${{ inputs.tf-workspace }}-${{ inputs.stage }}-errored.tfstate
      path: ${{ inputs.tf-root-dir }}/**/errored.tfstate
      if-no-files-found: ignore
