---
name: 'Repo signature Scan'
description: |
  The following Git Action performs a signature scan on the current directory.
inputs:
  projectName:
    description: "Name to be used for the project in Black Duck"
    required: true
  codeLocationSuffix:
    description: "Name to be used for the version in Black Duck"
    required: true
  tags:
    description: "Includes relevant information regarding the project distribution for license categorization"
    required: false
    default: "none"
  releaseTag:
    description: "ID of the currently released version. In case a merge to master was he trigger of the action, 'nonrelease' should be passed"
    required: true
  blackDuckToken:
    description: "Token used to submit the scans to black duck dashboards"
    required: true
  blackDuckURL:
    description: "URL from the Black Duck Dashboards where the scans will be deployed"
    required: true
    default: "https://bdh.aws.cloud.vwgroup.com"
  userGroup:
    description: "User group to which the project should be assigned"
    required: true
    default: "cap"
  groupName:
    description: "Project group name to which the project should be assigned"
    required: false
    default: "none"
  parentProjectName:
    description: "Parent project name to which the project should be assigned."
    required: false
    default: "none"
  parentProjectVersionName:
    description: "Parent project version name to which the project should be assigned."
    required: false
    default: "main"
  codeLocationName:
    description: "Sets the name for the created scan. If nothing given uses the name for the version"
    required: false
    default: 0
  isRelease:
    description: "true/false value that checks if it is a release. Defaults to false."
    required: false
    default: false
  mainBranchName:
    description: "Name given to main branch."
    required: false
    default: main
  excludedDirectories:
    description: "A comma separated list of directories to be excluded from scan, e.g. src/test,.github"
    required: false
    default: "tests/,.devcontainer/,**/setuptools,**/_distutils_hack,**/pkg_resources,**/pip"
  shouldGenerateReport:
    description: "Boolean value to generate reports at <reportPath>. Default: false. Also see: https://devstack.vwgroup.com/confluence/pages/viewpage.action?pageId=1745096719"
    required: false
    default: true
  tokenConfluence:
    description: "Confluence token"
    required: true
  reportPath:
    description: "Path to store the notices report. Also see: https://devstack.vwgroup.com/confluence/pages/viewpage.action?pageId=1745096719"
    required: false
    default: "./report"
  confluenceUsername:
    description: "Username which is used to upload the required BlackDuck files to confluence"
    required: true
  repoName:
    description: "Name of the repo. Is used to categorise releases."
    required: true
  confluencePageId:
    description: "PageId to which BlackDuck files are uploaded"
    required: true
  confluenceSpace:
    description: "Confluence space where the artifacts should be uploaded to"
    required: true
  scanPrefix:
    required: false
    description: "Used to properly distinguish the uploaded files, when you have to run more than one scan for each release"
  detectTimeout:
    description: "The timeout for the detect job which is passed to --detect.timeout"
    required: false
    default: 3600
  removeTestFiles:
    description: "Specify whether the requirement files located in test directories should be deleted or not"
    required: false
    default: false
  ignoreFailingComponents:
    description: "Specify whether the to ignore failing py install components"
    required: false
    default: false
  working-directory:
    description: 'Directory to work in'
    required: false
    default: "."
  devstack-user:
    description: 'Devstack user ID'
    required: true
  devstack-artifactory-token:
    description: 'Devstack token jfrog artifactory'
    required: true
  skip-plausi-check:
    description: 'Skips the Plausi Check validation'
    required: false
    default: false
  upload-plausicheck-results:
    description: 'Whether to upload PlausiCheck artifacts to GitHub'
    required: false
    default: true
  cleanup:
    description: 'Cleanup'
    required: false
    default: true
  pipRequirementsPath:
    description: "Path(s) to pip requirements file(s), passed to --detect.pip.requirements.path. Use commas for multiple paths."
    required: false
    default: ""
  enableSnippetMatching:
    description: "Enable Black Duck signature scanner snippet matching (true/false)"
    required: false
    default: false

runs:
  using: "composite"
  steps:
  - name: Create Timestamp # to support multiple runs in one job
    shell: bash
    run: |
      timestamp=$(date +%Y%m%d%H%M%S)
      echo "timestamp=$timestamp" >> "$GITHUB_ENV"
  - name: Create Temp Dir
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: mkdir blackduck_tmp
  - name: Get Detect Script
    shell: bash
    working-directory: ${{ inputs.working-directory }}/blackduck_tmp
    run: |
      curl -s -L -O https://detect.blackduck.com/detect10.sh
      chmod +x detect10.sh

  - name: Find Requirements Files
    shell: bash
    run: |
      pipRequirementsPath="${{ inputs.pipRequirementsPath }}"
      removeTestFiles="${{ inputs.removeTestFiles }}"
      if [ -n "$pipRequirementsPath" ]; then
      echo "Using user-provided pip requirements path: $pipRequirementsPath"
      echo "$pipRequirementsPath" | tr ',' '\n' > requirementFilesList.txt
      else
      echo "No pipRequirementsPath provided — scanning repo for requirements.txt files..."
      if [ "$removeTestFiles" = "true" ]; then
       find "$(pwd)" -name "requirements.txt" | sed -En '/test|tests|.terraform/!p' > requirementFilesList.txt
      else
       find "$(pwd)" -name "requirements.txt" > requirementFilesList.txt
      fi
      fi
      echo "Using the following requirements.txt files:"
      cat requirementFilesList.txt || echo "No files found."
      reqListVar=$(tr '\n' ',' < requirementFilesList.txt | sed '$ s/,$//')
      echo "reqListVar=$reqListVar" >> $GITHUB_ENV
  - name: Install Python Requirements
    shell: bash
    run: |
      echo "Creating and activating Python virtual environment..."
      python3 -m venv envScan
      source envScan/bin/activate
      echo "Dumping contents of each requirements.txt file:"
      while read file; do
      echo "--- $file ---"
      cat "$file"
      done < requirementFilesList.txt
      ignoreFailingComponents="${{ inputs.ignoreFailingComponents }}"
      if [ "$ignoreFailingComponents" = "true" ]; then
      sed -e 's/^/cat /' requirementFilesList.txt -e 's/$/ | xargs -n 1 pip install --no-warn-conflicts || true/' > scriptInstalling.sh
      else
      sed -e 's/^/pip install -r /' requirementFilesList.txt > scriptInstalling.sh
      fi
      echo "Generated install script:"
      cat scriptInstalling.sh
      chmod +x scriptInstalling.sh
      ./scriptInstalling.sh
      echo "Installed Python packages in envScan:"
      pip freeze | grep -v "pkg-resources" || true
      pip list

  - name: Show Installed Python Packages
    shell: bash
    run: |
      source envScan/bin/activate
      echo "Installed packages:"
      pip freeze

  - name: Calculate Version Name
    shell: bash
    run: |
      if [ "${{ inputs.releaseTag }}" = "${{ inputs.mainBranchName }}" ]; then
      VERSION_NAME="${{ inputs.mainBranchName }}-${{ github.run_number }}"
      else
      VERSION_NAME="${{ inputs.releaseTag }}"
      fi
      echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

  - name: Run Black Duck Scan
    shell: bash
    run: |
      mkdir -p "${{ inputs.reportPath }}"
      isRelease="${{ inputs.isRelease }}"
      releaseArgs=()
      if [ "$isRelease" = "true" ]; then
        releaseArgs+=("--detect.project.version.phase=RELEASED")
        releaseArgs+=("--detect.project.clone.categories=ALL")
        releaseArgs+=("--detect.clone.project.version.name=${{ inputs.mainBranchName }}")
        releaseArgs+=("--detect.policy.check.fail.on.severities=ALL")
      fi
      enableSnippetMatching="${{ inputs.enableSnippetMatching }}"
        snippetArgs=()
        if [ "$enableSnippetMatching" = "true" ]; then
        snippetArgs+=(--detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING)
      fi
      groupingArgs=()
      if [ "${{ inputs.groupName }}" != "none" ]; then
        groupingArgs+=("--detect.project.group.name=${{ inputs.groupName }}")
      fi
      parentProjectArgs=()
      if [ "${{ inputs.parentProjectName }}" != "none" ]; then
        parentProjectArgs+=("--detect.parent.project.name=${{ inputs.parentProjectName }}")
        parentProjectArgs+=("--detect.parent.project.version.name=${{ inputs.parentProjectVersionName }}")
      fi
      source envScan/bin/activate
      pip list
      scan_status=0
      bash ./blackduck_tmp/detect10.sh \
        --blackduck.url="${{ inputs.blackDuckURL }}" \
        --blackduck.api.token="${{ inputs.blackDuckToken }}" \
        --blackduck.trust.cert=true \
        --detect.project.name="${{ inputs.projectName }}" \
        --detect.project.version.name="${VERSION_NAME}" \
        --detect.project.tags="${{ inputs.tags }}" \
        --detect.project.force.update=true \
        --detect.project.user.groups="${{ inputs.userGroup }}" \
        --detect.source.path="." \
        --detect.code.location.name="${{ inputs.projectName }}/${VERSION_NAME}" \
        --detect.tools=DETECTOR,SIGNATURE_SCAN \
        --detect.blackduck.scan.mode=INTELLIGENT \
        --detect.detector.search.depth=10 \
        --detect.timeout="${{ inputs.detectTimeout }}" \
        --detect.excluded.directories=${{ inputs.excludedDirectories }} \
        --detect.project.version.update=true \
        --detect.wait.for.results=true \
        --detect.cleanup=true \
        --detect.project.version.distribution=INTERNAL \
        --detect.python.resolve.dependencies=true \
        --detect.accuracy.required=ALL \
        --detect.pip.requirements.path=$reqListVar \
        --blackduck.output.sbom.format=SPDX_JSON \
        --blackduck.output.sbom.file=${{ inputs.working-directory }}/blackduck_tmp/sbom.spdx.json \
        --detect.blackduck.generate.notices=true \
        --detect.notices.report="${{ inputs.shouldGenerateReport }}" \
        --detect.notices.report.path=${{ inputs.working-directory }}/blackduck_tmp \
        --detect.risk.report.pdf="${{ inputs.shouldGenerateReport }}" \
        --detect.risk.report.pdf.path=${{ inputs.working-directory }}/blackduck_tmp \
        --detect.policy.report.pdf="${{ inputs.shouldGenerateReport }}" \
        --detect.policy.report.pdf.path=${{ inputs.working-directory }}/blackduck_tmp \
        --detect.json.result.path="${{ inputs.working-directory }}/blackduck_tmp/blackduck-results.json" \
        "${snippetArgs[@]}" \
        "${releaseArgs[@]}" \
        "${groupingArgs[@]}" \
        "${parentProjectArgs[@]}" \
        2>&1 | tee blackduck_tmp/bdhscan.txt || scan_status=$?

      echo "scan_status=$scan_status" >> $GITHUB_ENV

  - name: Extract Version Link
    if: ${{ inputs.skip-plausi-check != 'true' }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      if [ -f blackduck_tmp/blackduck-results.json ]; then
      echo "Parsing components URL from blackduck-results.json..."
      version_link=$(jq -r '.projectVersion.componentsUrl' blackduck_tmp/blackduck-results.json)
      else
      echo "blackduck-results.json missing. Falling back to parsing bdhscan.txt log..."
      version_link=$(grep 'Black Duck Project BOM:' blackduck_tmp/bdhscan.txt | sed 's/.*: //')
      fi
      if [ -z "$version_link" ]; then
      echo "ERROR: Could not extract Black Duck components URL from JSON or logs."
      exit 1
      fi
      echo "version_link=$version_link"
      echo "version_link=$version_link" >> "$GITHUB_ENV"
      echo "Link to project version in OSS Scanning Software (e.g. Black Duck):" > blackduck_tmp/blackduck_oss_scanner_url.txt
      echo "$version_link" >> blackduck_tmp/blackduck_oss_scanner_url.txt

  - name: Download SBOM from Black Duck server (Bearer Auth)
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      BDH_TOKEN: ${{ inputs.blackDuckToken }}
      BDH_SERVER_URL: ${{ inputs.blackDuckURL }}
    run: |
      echo "::add-mask::$BDH_TOKEN"
      echo "BDH_TOKEN length: ${#BDH_TOKEN}"
      if [ -z "$BDH_TOKEN" ]; then
      echo "ERROR: BDH_TOKEN is not set!"
      exit 1
      fi
      echo "Authenticating to get bearer token..."
      auth_response=$(curl -ks -X POST \
      --header "Content-Type:application/json" \
      --header "Authorization: token $BDH_TOKEN" \
      "$BDH_SERVER_URL/api/tokens/authenticate")
      echo "Auth response: $auth_response"
      bearer_token=$(echo "$auth_response" | jq -r '.bearerToken')
      if [ -z "$bearer_token" ] || [ "$bearer_token" == "null" ]; then
      echo "ERROR: Failed to retrieve bearer token."
      exit 1
      fi
      echo "::add-mask::$bearer_token"
      echo "Reading version link from file..."
      version_link=$(sed -n '2p' blackduck_tmp/blackduck_oss_scanner_url.txt)
      echo "Original components link: $version_link"
      version_api_root="${version_link%/components}"
      echo "API root: $version_api_root"
      sbom_url="${version_api_root}/sbom?format=SPDX_JSON"
      echo "SBOM download URL: $sbom_url"
      echo "Downloading SBOM from Black Duck server..."
      curl -k -H "Authorization: bearer $bearer_token" "$sbom_url" -o blackduck_tmp/sbom.spdx.json
      echo "Downloaded SBOM to blackduck_tmp/sbom.spdx.json"

  - name: Download CycloneDX SBOM (XML) from Black Duck server
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      BDH_TOKEN: ${{ inputs.blackDuckToken }}
    run: |
      echo "::add-mask::$BDH_TOKEN"
      echo "Reading version link from file..."
      version_link=$(sed -n '2p' blackduck_tmp/blackduck_oss_scanner_url.txt)
      echo "Original components link: $version_link"
      version_api_root="${version_link%/components}"
      echo "API root: $version_api_root"
      mkdir -p blackduck_tmp
      sbom_cyclonedx_url="${version_api_root}/sbom?format=CYCLONEDX_XML"
      echo "Downloading CycloneDX SBOM (XML)..."
      curl -k -H "Authorization: token $BDH_TOKEN" "$sbom_cyclonedx_url" -o blackduck_tmp/bom.cyclonedx.xml
      echo "Downloaded CycloneDX SBOM to blackduck_tmp/bom.cyclonedx.xml"

  - name: Login to Devstack-Docker-Artifactory
    if: ${{ inputs.skip-plausi-check != 'true' }}
    uses: docker/login-action@v3
    with:
      registry: bdh-docker.docker.devstack.vwgroup.com
      username: ${{ inputs.devstack-user }}
      password: ${{ inputs.devstack-artifactory-token }}

  - name: Run Plausi Check
    if: ${{ inputs.skip-plausi-check != 'true' }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    env:
      BDH_TOKEN: ${{ inputs.blackDuckToken }}
    run: |
      work_path=`pwd`
      docker run --mount type=bind,source="${work_path}/blackduck_tmp",target=/data \
      bdh-docker.docker.devstack.vwgroup.com/plausicheck \
      $version_link \
      $BDH_TOKEN
      echo "<details>" > $GITHUB_STEP_SUMMARY
      echo "<summary>PlausiCheck-Report</summary>" >> $GITHUB_STEP_SUMMARY
      cat blackduck_tmp/PlausiCheck_BDH.html >> $GITHUB_STEP_SUMMARY
      echo "</details>" >> $GITHUB_STEP_SUMMARY

  - name: List Black Duck Tmp Folder
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      echo "Listing contents of blackduck_tmp:"
      ls -l blackduck_tmp

  - name: Archive production artifacts
    if: ${{ inputs.skip-plausi-check != 'true' && inputs.upload-plausicheck-results == 'true' }}
    uses: actions/upload-artifact@v6
    with:
      name: ${{ github.job }}-plausi-check-results_${{ env.timestamp }}
      path: |
        ${{ inputs.working-directory }}/blackduck_tmp/PlausiCheck_BDH.json
        ${{ inputs.working-directory }}/blackduck_tmp/PlausiCheck_BDH.html
        ${{ inputs.working-directory }}/blackduck_tmp/PlausiCheck_BDH.log
        ${{ inputs.working-directory }}/blackduck_tmp/blackduck_oss_scanner_url.txt
        ${{ inputs.working-directory }}/blackduck_tmp/*RiskReport.pdf
        ${{ inputs.working-directory }}/blackduck_tmp/*Notices_Report.txt

  - name: CleanUp
    if: ${{ inputs.cleanup == 'true' }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      rm -rf blackduck_tmp
      rm -f detect10.sh bdhscan.txt
