---
name: 'Find and scan the requirement files from a repository'
description: |
  The following Git Action performs a scan of the python requirement files using Black Duck. It is required to have
    done the check out of the main repository before running the action, and that its directory is placed within the
    current location.
inputs:
  projectName:
    description: "Name to be used for the project in Black Duck"
    required: true
  codeLocationSuffix:
    description: "Name to be used for the version in Black Duck"
    required: true
  tags:
    description: "Includes relevant information regarding the project distribution for license categorization"
    required: false
    default: "none"
  removeTestFiles:
    description: "Specify whether the requirement files located in test directories should be deleted or not"
    required: false
    default: false
  blackDuckToken:
    description: "Token used to submit the scans to black duck dashboards"
    required: true
  blackDuckURL:
    description: "URL from the Black Duck Dashboards where the scans will be deployed"
    required: true
  releaseTag:
    description: "ID of the currently released version. In case a merge to master was he trigger of the action, 'nonrelease' should be passed"
    required: true
  userGroup:
    description: "User group to which the project should be assigned"
    required: true
    default: "cap"
  groupName:
    description: "Project group name to which the project should be assigned"
    required: true
    default: "cap"
  codeLocationName:
    description: "Sets the name for the created scan. If nothing given uses the name for the version"
    required: false
    default: 0
  ignoreFailingComponents:
    description: "Do not fail WF when installing an incompatible component (Mitigated if doing a Docker scan)"
    required: false
    default: false
  isRelease:
    description: "true/false value that checks if it is a release. Defaults to false."
    required: false
    default: false
  mainBranchName:
    description: "Name given to main branch."
    required: false
    default: main
  excludedDirectories:
    description: "A comma separated list of directories to be excluded from scan, e.g. src/test,.github"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
  - name: "Find requirements.txt files and install them. Furthermore run pip detect on them"
    shell: bash
    run: |
      python3 -m venv envScan
      source envScan/bin/activate
      pip list
      python -m pip install --upgrade pip setuptools wheel
      pip list
      if ${{ inputs.removeTestFiles }};
      then
      find "$(cd .; pwd)" -name "requirements.txt" | sed -En '/test|tests|.terraform/!p' > requirementFilesList.txt;
      else
      find "$(cd .; pwd)" -name "requirements.txt" > requirementFilesList.txt;
      fi
      if ${{ inputs.ignoreFailingComponents }};
      then
      sed -e 's/^/cat /' requirementFilesList.txt -e 's/$/ | xargs -n 1 pip install --no-warn-conflicts || true/' > scriptInstalling.sh
      else
      sed -e 's/^/pip install -r /' requirementFilesList.txt > scriptInstalling.sh
      fi
      reqListVar=$(tr '\n' ',' < requirementFilesList.txt | sed '$ s/.$//')
      chmod +x scriptInstalling.sh
      ./scriptInstalling.sh
      pip list
      releaseArgs=()
      if [ ${{inputs.isRelease}} == "true" ];then
        releaseArgs+=( "--detect.project.version.phase=RELEASED" )
        releaseArgs+=( "--detect.project.clone.categories=ALL" )
        releaseArgs+=( "--detect.clone.project.version.name=${{inputs.mainBranchName}}" )
        releaseArgs+=( "--detect.policy.check.fail.on.severities=ALL" )
      fi
      bash <(curl -s https://detect.blackduck.com/detect9.sh) \
      --blackduck.url=${{ inputs.blackDuckURL }} \
      --blackduck.api.token=${{ inputs.blackDuckToken }} \
      --detect.project.name=${{ inputs.projectName }} \
      --detect.project.version.name=${{ inputs.releaseTag }} \
      --detect.project.tags=${{ inputs.tags }} \
      --detect.code.location.name=${{ inputs.projectName }}/${{ inputs.releaseTag }}/${{ inputs.codeLocationSuffix }} \
      --detect.pip.requirements.path=$reqListVar \
      --detect.tools=DETECTOR \
      --detect.excluded.directories=${{ inputs.excludedDirectories }} \
      --detect.project.user.groups=${{ inputs.userGroup }} \
      --detect.project.group.name=${{ inputs.groupName }} ${releaseArgs[@]}
      deactivate
