---
name: "Upload deployment artifacts"
description: "upload artifacts to s3 bucket"
inputs:
  project-name:
    description: "Name of project"
    required: true
  workspace:
    description: "workspace name"
    required: true
  source-code-bucket:
    description: "source code bucket"
    required: true
runs:
  using: "composite"
  steps:
  - name: setup deploy path
    shell: bash
    run: |
      workspace="${{ inputs.workspace }}"
      if [ $workspace = "default" ]
      then
        echo "default workspace"
        echo "deploy_path=s3://${{ inputs.source-code-bucket }}/cas-etl/projects/${{ inputs.project-name }}" >> $GITHUB_OUTPUT
      else
        echo "workspace:"
        echo $workspace
        echo "deploy_path=s3://${{ inputs.source-code-bucket }}/cas-etl/projects/${{ inputs.project-name }}/workspaces/${{ inputs.workspace }}" >> $GITHUB_OUTPUT
      fi
    id: set-deploy-path

  - name: Clean deployment directory
    shell: bash
    run: |
      workspace="${{ inputs.workspace }}"
      if [ $workspace = "default" ]
      then
        echo $workspace
        aws s3 rm ${{ steps.set-deploy-path.outputs.deploy_path }} --recursive --exclude "workspaces/*"
      else
        aws s3 rm ${{ steps.set-deploy-path.outputs.deploy_path }} --recursive
      fi
  - name: upload common library
    shell: bash
    run: aws s3 sync ./${{ inputs.project-name }}-common-jar ${{ steps.set-deploy-path.outputs.deploy_path }}/common/
  - name: upload etl source code
    shell: bash
    run: aws s3 sync ./${{ inputs.project-name }}-job-source-code ${{ steps.set-deploy-path.outputs.deploy_path }}/
  - name: upload etl source code
    shell: bash
    run: aws s3 sync ./${{ inputs.project-name }}-metadata ${{ steps.set-deploy-path.outputs.deploy_path }}/casETLMetaData/
  - name: upload pyScripts
    shell: bash
    run: aws s3 sync ./${{ inputs.project-name }}-pyScripts ${{ steps.set-deploy-path.outputs.deploy_path }}/pyScripts/
